project_name: agent
builds:
  - env:
    - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows/amd64

# $ GORELEASER_CURRENT_TAG=v1.2.3 goreleaser build --rm-dist --skip-validate